name: Validate
description: Deploy and Validate test app

runs:
  using: "composite"
  steps:
    - name: Deploy Test app and Verify install
      run: |
        set -x 
        kubectl apply -f ./tests/test.yaml
        x=1
        while [[] $(kubectl get pods -l kontain=test-app -o 'jsonpath={..status.conditions[?(@.type=="Ready")].status}') != "True" ]] && [[ x -le 120 ]]
        do 
          echo "waiting for pod"
          sleep 1
          x=$(( $x + 1 ))
        done
        kubectl exec deployment.apps/kontain-test-app -- uname -r | egrep -q -e '.*\.kontain\.(KKM|KVM)$' && echo success|| exit 1
      shell: bash
