name: Deploy Kontain
description: Generate and apply Kontain deployment

runs:
  using: "composite"
  steps:
    - name: Build kkm and kkm_test
      run: |
        ./kontain-kustomize.sh --deploy-location=./kontain-deploy
        status=$(kubectl get pod -A  -l app=kontain-init  -o jsonpath="{.items[0].status.phase}")
        echo "Pod status: $status"
        if [ $status != 'Running' ] ; then 
          pod=$(kubectl get pod -A  -l app=kontain-init -o jsonpath="{.items[0].metadata.name}")
          kubectl logs $pod -n kube-system 
          exit 1
        fi
        pod=$(kubectl get pod -A  -l app=kontain-init -o jsonpath="{.items[0].metadata.name}")
        kubectl logs $pod -n kube-system
      shell: bash
