name: Deploy Kontain
description: Generate and apply Kontain deployment

runs:
  using: "composite"
  steps:
    - name: Build kkm and kkm_test
      run: |
        set -x
        ./kontain-kustomize.sh --deploy-location=./kontain-deploy
        # wait for pod to complete initialization
        while [ -z "$status" ]
        do 
                echo "."
                sleep 1
                log=$(kubectl logs -l app=kontain-init -n kube-system 2>/dev/null)
                echo "log = $log" 
                status="$(echo $log | grep 'kontain-init completed')"
                echo "status = $status"
        done
        kubectl logs -l app=kontain-init -n kube-system
      shell: bash
