name: Deploy Kontain
description: Generate and apply Kontain deployment

runs:
  using: "composite"
  steps:
    - name: Build kkm and kkm_test
      run: |

        ./kontain-kustomize.sh --deploy-location=./kontain-deploy

        pname=$(kubectl get pod -l app=kontain-init -o jsonpath="{.items[0].metadata.name}" -n kube-system)
        kubectl logs -n kube-system ${pname}

      shell: bash {0}
