name: Deploy Kontain
description: Generate and apply Kontain deployment

runs:
  using: "composite"
  steps:
    - name: Build kkm and kkm_test
      run: |

        ./kontain-kustomize.sh --deploy-location=./kontain-deploy

      shell: bash {0}
