# Copyright 2022 Kontain
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#      http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.
apiVersion: v1
kind: ConfigMap
metadata:
  name: kontain-snapshot-entrypoint
  namespace: kontain-snapshot-ns
  labels:
    app: snapshot-maker
data:
  entrypoint.sh: |
    #!/usr/bin/env bash

    [ "$TRACE" ] && set -x

    set -x 

    # wait for kmpipe socket to be created
    until [ -S /root/$SNAPDIR_HOST/kmpipe* ]
    do
        sleep 5
    done

    # wait for target pod to start fully and reply to end point 
    until curl --output /dev/null --silent --fail $URL; do
        printf '.'
        sleep 5
    done

    # to let snapshot cto calm down after the curl 
    sleep 5

    chroot /root /bin/bash -c /scripts-lib/runner.sh

    mkdir -p $SNAPDIR_CONTAINER
    mv /root/$SNAPDIR_HOST/kmsnap* $SNAPDIR_CONTAINER/

    touch /tmp/kontain-snapshot-ready

    sleep infinity

---
apiVersion: v1
kind: ConfigMap
metadata:
  name: kontain-snapshot-runner
  namespace: kontain-snapshot-ns
  labels:
    app: snapshot-maker
data:
  runner.sh: |
    #!/usr/bin/env bash

    [ "$TRACE" ] && set -x

    set -x

    pipe_file=$(ls $SNAPDIR_HOST/kmpipe.*|sort -n |tail -1)
    echo pipe_file = $pipe_file
    /opt/kontain/bin/km_cli -r -s $pipe_file
