# Copyright 2022 Kontain
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#      http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.
apiVersion: apps/v1
kind: DaemonSet
metadata:
  name: kontain-node-initializer
  namespace: kube-system
  labels:
    app: kontain-init
spec:
  selector:
    matchLabels:
      app: kontain-init
  updateStrategy:
    type: RollingUpdate
  template:
    metadata:
      labels:
        name: kontain-node-initializer
        app: kontain-init
    spec:
      containers:
        - image: centos:7 # ubuntu:18.04
          name: node-initializer
          command: ["/scripts/entrypoint.sh"]
          envFrom:
            - configMapRef:
                name: env-configmap
          securityContext:
            privileged: true
          volumeMounts:
            - name: root-mount
              mountPath: /root
            - name: systemd
              mountPath: /run/systemd
            - name: lib-entrypoint-install
              mountPath: /root/scripts-lib/kontain-install-artifacts.sh
              subPath: kontain-install-artifacts.sh
            - name: lib-runtime-config
              mountPath: /root/scripts-lib/runtime-config.sh
              subPath: runtime-config.sh
            - name: lib-runtime-restart
              mountPath: /root/scripts-lib/runtime-restart.sh
              subPath: runtime-restart.sh
            - name: lib-kvm-kkm-install
              mountPath: /root/scripts-lib/kvm-kkm-install.sh
              subPath: kvm-kkm-install.sh
            - name: lib-pre-install
              mountPath: /root/scripts-lib/pre-install.sh
              subPath: pre-install.sh
            - name: entrypoint
              mountPath: /scripts
      volumes:
        - name: root-mount
          hostPath:
            path: /
        - name: systemd
          hostPath:
            path: /run/systemd
        - name: entrypoint
          configMap:
            name: kontain-install-entrypoint
            defaultMode: 0744
        - name: lib-entrypoint-install
          configMap:
            name: kontain-install-artifacts
            defaultMode: 0744
        - name: lib-runtime-config
          configMap:
            name: kontain-runtime-config
            defaultMode: 0744
        - name: lib-runtime-restart
          configMap:
            name: kontain-runtime-restart
            defaultMode: 0744
        - name: lib-kvm-kkm-install
          configMap:
            name: kontain-kvm-kkm-install
            defaultMode: 0744
        - name: lib-pre-install
          configMap:
            name: pre-install
            defaultMode: 0744
