apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
  - entry-point.yaml
  - cm-install-lib.yaml
  - cm-containerd-install.yaml
  - containerd-cfg-get.yaml
  - containerd-cfg-update.yaml
  - containerd-restart.yaml
  - runtime-class.yaml
  - kontain-deploy.yaml

configMapGenerator:
  - name: env-config-map
    namespace: kube-system
    envs:
      - config.properties
# configMapGenerator:
#   - name: env-config-map
#     namespace: kube-system
#     files:
#       - config.properties
